version: '3.9'

services:
  mongodb:
    image: mongo:5.0.8
    ports:
      - "27017:27017"
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    restart: always

  api:
    build:  
      context: .
    ports:
      - 5000:5000
    restart: always
    depends_on: 
      - mongodb
    volumes:
      - .:/app
